### ISSUE TITLE
datacamp logo

### ISSUE THREAD

**Issue by chendaniely** [chendaniely/chendaniely.github.io#24]
@hugobowne I want to put a comment about the DC course and want to use a logo.
Is there any licence/copyright of using a DC logo? can I put the image in this repo? or do I need to hotlink it somewhere?

**Comment by hugobowne** [comment]
@chendaniely what's the context? by DC you mean DataCamp, right? where do you want to use the logo?

**Comment by chendaniely** [comment]
DataCamp logo in like the about/projects section on my website: (for example bottom of this page: http://chendaniely.github.io/about/)

**Comment by hugobowne** [comment]
ha! i clearly saw the question and not title of issue :-D . I'll get back to you ASAP about this

**Comment by chendaniely** [comment]
I think you emailed me about putting something on my website. just making sure that I have someone's blessings :)

**Comment by hugobowne** [comment]
You have our blessing! In fact, DC MGMT says 'Hellz yea!!'. Feel free to put image in repo. Get high quality image here: https://www.datacamp.com/brand

**Comment by chendaniely** [comment]
:+1:
